project_id = "sugpsvakosdaciiovwjk"

[functions.send-email]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.create-study-session]
verify_jwt = false