// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sugpsvakosdaciiovwjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1Z3BzdmFrb3NkYWNpaW92d2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTgxNTYsImV4cCI6MjA3MTI3NDE1Nn0.USzEgLQZteza3qhFBwHVCLw0e0DtjlVTkQ2mL9g4oL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});